services:
  config-server:
    containerName: config-server
    image: vantaicn/spring-petclinic-config-server
    tag: latest
    port: 8888
    replicaCount: 1

  discovery-server:
    containerName: discovery-server
    image: vantaicn/spring-petclinic-discovery-server
    tag: latest
    port: 8761
    replicaCount: 1

  customers-service:
    containerName: customers-service
    image: vantaicn/spring-petclinic-customers-service
    tag: latest
    port: 8081
    replicaCount: 1

  visits-service:
    containerName: visits-service
    image: vantaicn/spring-petclinic-visits-service
    tag: latest
    port: 8082
    replicaCount: 1

  vets-service:
    containerName: vets-service
    image: vantaicn/spring-petclinic-vets-service
    tag: latest
    port: 8083
    replicaCount: 1

  api-gateway:
    containerName: api-gateway
    image: vantaicn/spring-petclinic-api-gateway
    tag: latest
    port: 8080
    replicaCount: 1

  admin-server:
    containerName: admin-server
    image: vantaicn/spring-petclinic-admin-server
    tag: latest
    port: 9090
    replicaCount: 1

ingress:
  enabled: true
  host: spring-petclinic
  namespace: default
  paths:
    - path: /
      service: api-gateway
