services:
  config-server:
    enabled: true
    containerName: config-server
    image: vantaicn/spring-petclinic-config-server
    tag: latest
    port: 8888
    replicaCount: 1

  discovery-server:
    enabled: true
    containerName: discovery-server
    image: vantaicn/spring-petclinic-discovery-server
    tag: latest
    port: 8761
    replicaCount: 1

  customers-service:
    enabled: true
    containerName: customers-service
    image: vantaicn/spring-petclinic-customers-service
    tag: latest
    port: 8081
    replicaCount: 1

  visits-service:
    enabled: true
    containerName: visits-service
    image: vantaicn/spring-petclinic-visits-service
    tag: latest
    port: 8082
    replicaCount: 1

  vets-service:
    enabled: true
    containerName: vets-service
    image: vantaicn/spring-petclinic-vets-service
    tag: latest
    port: 8083
    replicaCount: 1

  api-gateway:
    enabled: true
    containerName: api-gateway
    image: vantaicn/spring-petclinic-api-gateway
    tag: latest
    port: 8080
    replicaCount: 1

  admin-server:
    enabled: true
    containerName: admin-server
    image: vantaicn/spring-petclinic-admin-server
    tag: latest
    port: 9090
    replicaCount: 1

namespace: default

ingress:
  enabled: true
  host: spring-petclinic
  paths:
    - path: /
      service: api-gateway

configServerUrl: http://config-server:8888
zipkinTracingUrl: http://tracing-server.monitoring.svc.cluster.local:9411/api/v2/spans

prometheusScrapeTargets:
  - api-gateway
  - visits-service
  - vets-service
  - customers-service
