{{- range $name, $config := .Values.services }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $config.containerName }}
  namespace: {{ $.Values.namespace }}
spec:
  replicas: {{ default 1 $config.replicaCount }}
  selector:
    matchLabels:
      app: {{ $config.containerName }}
  template:
    metadata:
      labels:
        app: {{ $config.containerName }}
    spec:
      containers:
        - name: {{ $config.containerName }}
          image: {{ $config.image }}:{{ $config.tag }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ $config.port }}
          env:
            - name: CONFIG_SERVER_URL
              value: {{ $.Values.configServerUrl }}
            - name: EUREKA_INSTANCE_HOSTNAME
              value: {{ $config.containerName }}
            - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
              value: {{ $.Values.zipkinTracingUrl }}
            - name: MANAGEMENT_TRACING_SAMPLING_PROBABILITY
              value: "1.0"
            - name: MANAGEMENT_METRICS_TAGS_APPLICATION
              value: {{ $config.containerName }}
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
{{- end }}