{{- range $name, $config := .Values.services }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $config.containerName }}
spec:
  type: ClusterIP
  selector:
    app: {{ $config.containerName }}
  ports:
    - port: {{ $config.port }}
      targetPort: {{ $config.port }}
---
{{- end }}
