{{- range $name, $config := .Values.services }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $config.containerName }}
  {{- if has $config.containerName $.Values.prometheusScrapeTargets }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "{{ $config.port }}"
  {{- end }}
spec:
  type: ClusterIP
  selector:
    app: {{ $config.containerName }}
  ports:
    - port: {{ $config.port }}
      targetPort: {{ $config.port }}
---
{{- end }}
